# Laboratorio de evaluación de modelos de aprendizaje supervisado

Realice los siguientes ejercicios para consolidar sus conocimientos y comprensión de la evaluación de modelos de aprendizaje supervisado.

In [81]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Evaluación de modelos de regresión

In [83]:
# URL del dataset de Boston hoyusing data
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"

# Nombres de las columnas
column_names = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX",
    "PTRATIO", "B", "LSTAT", "MEDV"
]

# Cargar el dataset en un DataFrame
data = pd.read_csv(url, delim_whitespace=True, header=None, names=column_names)

X = data.drop("MEDV", axis=1)
y = data["MEDV"]

data = pd.concat([X, y], axis=1)

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


## 1. Divida este conjunto de datos en conjuntos de train (80%) y de test (20%).

El campo `MEDV` representa el valor medio de las viviendas ocupadas por sus propietarios (en miles de dólares) y es la variable objetivo que queremos predecir.

In [86]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.metrics import accuracy_score, balanced_accuracy_score, precision_score, f1_score, recall_score, confusion_matrix

In [87]:
# X = data.drop("MEDV", axis=1)
# y = data["MEDV"] -> Objetivo

# Dividir conjunto de datos con train_test_split en datos entrenamiento/prueba (80%/20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=31071989)

## 2. Entrene un modelo `LinearRegression` en este conjunto de datos y genere predicciones tanto en el conjunto de entrenamiento como en el de prueba.

In [89]:
# Entrenar Modelo Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

# Predicciones entrenamiento
y_pred_train= model.predict(X_train)

# Predicciones Pruebas
y_pred_test = model.predict(X_test)

## 3. Calcule e imprima R-cuadrado tanto para el conjunto de entrenamiento como para el de prueba.

In [91]:
# Métricas (mean_squared_error, r2_score, mean_absolute_error)

## Entrenamiento
r2_train = r2_score(y_train, y_pred_train)

## Test
r2_test = r2_score(y_test, y_pred_test)

print(f"R2 Score Train: {r2_train} vs R2 Score Test: {r2_test}")
# VARIABILIDAD (0-1, más cerca de 1 mejor ajuste): R2 Score Train: 0.7452254954385831 vs R2 Score Test: 0.7072549575355775
# Buen ajuste, ligeramente superior para datos entrenamiento

R2 Score Train: 0.7452254954385831 vs R2 Score Test: 0.7072549575355775


## 4. Calcule e imprima el error cuadrático medio para el conjunto de entrenamiento y de prueba.

In [93]:
## Entrenamiento
mse_train = mean_squared_error(y_train, y_pred_train)

## Test
mse_test = mean_squared_error(y_test, y_pred_test)

print(f"MSE Train: {mse_train} vs MSE Test: {mse_test}")
# PROMEDIO ERRORES CUADRADOS (Más bajo = mejor ajuste, penaliza errores grandes)
# Buen ajuste, ligeramente superior para datos entrenamiento

MSE Train: 21.798899395961175 vs MSE Test: 23.366454865016184


## 5. Calcule e imprima el error medio absoluto para el conjunto de entrenamiento y de prueba.

In [95]:
## Entrenamiento
mae_train = mean_absolute_error(y_train, y_pred_train)

## Test
mae_test = mean_absolute_error(y_test, y_pred_test)

print(f"MaE Train: {mae_train} vs MaE Test: {mae_test}")
# PROMEDIO ERRORES ABSOLUTOS (Más bajo = mejor precisión, medida magnitud error): 
# La predicción se desvía en 3.28 mil $ en entrenamiento y 3.53 mil $ en test. 

MaE Train: 3.2760151541092073 vs MaE Test: 3.5309236021086723


## Evaluación del modelo de clasificación

In [97]:
from sklearn.datasets import load_iris

data = load_iris()

X_c = pd.DataFrame(data["data"], columns=data["feature_names"])
y_c = pd.DataFrame(data["target"], columns=["class"])

datac = pd.concat([X_c, y_c], axis=1)

In [98]:
datac.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

## 6. Divida este conjunto de datos en conjuntos de train (80%) y de test (20%).

El campo `class` representa el tipo de flor y es la variable objetivo que querremos predecir.

In [100]:
X_c = pd.DataFrame(data["data"], columns=data["feature_names"])
y_c = pd.DataFrame(data["target"], columns=["class"])

X_train, X_test, y_train, y_test = train_test_split(X_c, y_c, test_size=0.2, random_state=31071989)

In [101]:
! pip install plotly

In [137]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
plt.figure(figsize=(8,8))
pd.options.plotting.backend = "plotly"
sns.set(rc={'figure.figsize':(6,6)});

<Figure size 800x800 with 0 Axes>

In [139]:
# Your code here

## 7. Entrene un modelo `LogisticRegression` en este conjunto de datos y genere predicciones tanto en el conjunto de entrenamiento como en el de prueba.

In [142]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter = 1000) # Dejo que escoja el solver más adecuado automáticamente + entrenar el modelo 1000 veces
model.fit(X_train, y_train.values.ravel()) # Aplanamos para evitar ValueError: Found input variables with inconsistent numbers of samples: [30, 120]


# Predicciones entrenamiento
y_pred_train= model.predict(X_train)

# Predicciones Pruebas
y_pred_test = model.predict(X_test)

## 8. Calcule e imprima la puntuación de precisión tanto para el conjunto de entrenamiento como para el de pruebas.

    Esta función resuelve los ejercicios 8,9,10,11,12 y 13.

In [145]:
# Métricas (accuracy_score, balanced_accuracy_score, precision_score, f1_score, recall_score, confusion_matrix)
# PRECISIÓN / ACCURACY : Tasa de acierto total

## Entrenamiento
train_accuracy = accuracy_score(y_train, y_pred_train)
print(f"Train Accuracy: {train_accuracy}")

## Test
test_accuracy = accuracy_score(y_test, y_pred_test)
print(f"Test Accuracy: {test_accuracy}")

# El modelo ha clasificado correctamente el 95% de las muestras de entrenamoiento y el 96,6% de las de test!

Train Accuracy: 0.95
Test Accuracy: 0.9666666666666667


## 9. Calcule e imprima la puntuación de precisión equilibrada tanto para el conjunto de entrenamiento como para el de pruebas.

In [150]:
# PRECISIÓN EQUILIBRADA / BALANCED ACCURACY  Tasa de acierto por clase
train_balanced_accuracy = balanced_accuracy_score(y_train, y_pred_train)
print(f"Train Balanced Accuracy: {train_balanced_accuracy}")

test_balanced_accuracy = balanced_accuracy_score(y_test, y_pred_test)
print(f"Test Balanced Accuracy: {test_balanced_accuracy}")

Train Balanced Accuracy: 0.94804318488529
Test Balanced Accuracy: 0.9722222222222222


## 10. Calcule e imprima la puntuación de precisión tanto para el conjunto de entrenamiento como para el de prueba.

In [162]:
# PRECISION
train_precision = precision_score(y_train, y_pred_train, average='weighted')
print(f"Train Precision: {train_precision}")

test_precision = precision_score(y_test, y_pred_test, average='weighted')
print(f"Test Precision: {test_precision}")



Train Precision: 0.95
Test Precision: 0.9694444444444444


## 11. Calcule e imprima la puntuación de recuerdo tanto para el conjunto de entrenamiento como para el de prueba.

In [164]:
# RECALL
train_recall = recall_score(y_train, y_pred_train, average='weighted')
print(f"Train Recall: {train_recall}")

test_recall = recall_score(y_test, y_pred_test, average='weighted')
print(f"Test Recall: {test_recall}")

Train Recall: 0.95
Test Recall: 0.9666666666666667


## 12. Calcule e imprima la puntuación F1 tanto para el conjunto de entrenamiento como para el de prueba.

In [168]:
train_f1 = f1_score(y_train, y_pred_train, average='weighted')
print(f"Train F1 Score: {train_f1}")

test_f1 = f1_score(y_test, y_pred_test ,average='weighted')
print(f"Test F1 Score: {test_f1}")


Train F1 Score: 0.95
Test F1 Score: 0.9666666666666667


## 13. Generar matrices de confusión tanto para el conjunto de entrenamiento como para el de pruebas.

In [174]:
train_confusion_matrix = confusion_matrix(y_train, y_pred_train)
print(f"Train Confusion Matrix:\n{train_confusion_matrix}")

test_confusion_matrix = confusion_matrix(y_test, y_pred_test)
print(f"Test Confusion Matrix:\n{test_confusion_matrix}")

Train Confusion Matrix:
[[43  0  0]
 [ 0 36  3]
 [ 0  3 35]]
Test Confusion Matrix:
[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]]


In [160]:
""" REPORTE : """
from sklearn.metrics import classification_report
reporte_train = classification_report(y_train, y_pred_train)
print(f"Reporte Test: = {reporte_train}")

reporte_test = classification_report(y_test, y_pred_test)
print(f"Reporte Test: = {reporte_test}")

Reporte Test: =               precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.92      0.92      0.92        39
           2       0.92      0.92      0.92        38

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120

Reporte Test: =               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



## Bonus: Para cada uno de los conjuntos de datos de este laboratorio, intente entrenar con algunos de los otros modelos que ha aprendido, vuelva a calcular las métricas de evaluación y compare para determinar qué modelos funcionan mejor en cada conjunto de datos.

In [209]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score # Validación cruzada

X_c = pd.DataFrame(data["data"], columns=data["feature_names"])
y_c = pd.DataFrame(data["target"], columns=["class"])

X_train, X_test, y_train, y_test = train_test_split(X_c, y_c, test_size=0.2, random_state=31071989)

models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
}

for nombre, modelo in models.items(): # Validación cruzada
    scores = cross_val_score(modelo, X_c, y_c.values.ravel(), cv=5, scoring='accuracy')
    print(f"Modelo: {nombre}, Precisión Media: {scores.mean():.2f}, Desviación Estándar: {scores.std():.2f}")


reportes = []
for nombre, modelo in models.items():
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    reporte = f"Modelo: {nombre}\n{classification_report(y_test, y_pred)}"
    reportes.append(reporte)

# print(reportes)
for reporte in reportes:
    print(f"{reporte}\n")


Modelo: Logistic Regression, Precisión Media: 0.97, Desviación Estándar: 0.02
Modelo: Decision Tree Classifier, Precisión Media: 0.96, Desviación Estándar: 0.03
Modelo: Random Forest Classifier, Precisión Media: 0.96, Desviación Estándar: 0.02
Modelo: Logistic Regression
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Modelo: Decision Tree Classifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.